import React, { useState } from "react";
import { useTranslation } from "react-i18next";
import { Copy, Check, Sparkles } from "lucide-react";
import { Modal } from "../../components/ui/Modal";
import { Button } from "../../components/ui/Button";
import { useToast } from "../../context/ToastContext";
import type { ConceptMap, Project } from "../../domain/types";

interface GenerateDocumentModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: Project;
  map: ConceptMap;
}

export const GenerateDocumentModal: React.FC<GenerateDocumentModalProps> = ({
  isOpen,
  onClose,
  project,
  map,
}) => {
  const { t } = useTranslation();
  const { showToast } = useToast();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const concepts = map.nodes.filter((n) => n.kind === "concept");
  const viability = map.nodes.filter((n) => n.kind === "viability");
  const risks = map.nodes.filter((n) => n.kind === "risk");

  const markdownContent = `# NEXO EXECUTIVE SUMMARY: ${project.name}

## Project Overview
${project.description || "Spatial concept workspace for " + project.name}

---

## Key Concepts (${concepts.length})
${concepts.map((c) => `- **${c.title}**: ${c.description} [${c.metadata}]`).join("\n") || "No core concepts mapped yet."}

## Viability Signals (${viability.length})
${viability.map((v) => `- **${v.title}**: ${v.description} [${v.metadata}]`).join("\n") || "No viability signals mapped."}

## Identified Risks (${risks.length})
${risks.map((r) => `- ⚠️ **${r.title}**: ${r.description} [${r.metadata}]`).join("\n") || "No risk points flagged."}

---
*Generated by Nexo Spatial AI Engine*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    showToast(t("common.copied"), "success");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`${t("canvas.generate")} — ${project.name}`}
      description="Executive report summary automatically generated from your concept map."
      maxWidth="lg"
    >
      <div className="space-y-4">
        {/* Document Preview Box */}
        <div className="p-4 rounded-2xl bg-elevated border border-line font-mono text-caption text-fg max-h-72 overflow-y-auto whitespace-pre-wrap leading-relaxed">
          {markdownContent}
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between pt-2 border-t border-line-soft">
          <span className="text-caption text-muted flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-concept-fg" />
            {map.nodes.length} concepts included
          </span>

          <div className="flex items-center gap-2">
            <Button type="button" variant="ghost" onClick={onClose}>
              {t("common.close")}
            </Button>
            <Button
              type="button"
              variant="primary"
              onClick={handleCopy}
              icon={copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            >
              {copied ? t("common.copied") : "Copy Markdown"}
            </Button>
          </div>
        </div>
      </div>
    </Modal>
  );
};
